[project]
name = "fdi-pln-2606-p1"
version = "1.0"
description = "Repositorio para la asignatura PLN"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "typer>=0.24.1",
]

[project.scripts]
fdi-pln-2606-p1 = "fdi_pln_2606_p1.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
