[project]
name = "fdi-pln-2606-p5"
version = "1.0"
description = "Práctica 5 - Transformer LLM + NER sobre el corpus de Alice in Wonderland"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Carmen Fernández", email = "carfer23@ucm.es" },
    { name = "Yushan Yang", email = "yushyang@ucm.es" },
]
dependencies = [
    "loguru>=0.7.3",
    "click>=8.1",
    "rich>=13.0",
    "torch",
    "numpy>=2.4.6",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }

# Para construir el wheel:

[build-system]
requires = ["uv_build>=0.11.3,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[project.scripts]
fdi-pln-2606-p5 = "src.main:cli"
